# Frozen Lake Problem
Winter is here. You and your friends were tossing around a frisbee at the park when you made a wild throw that left the frisbee out in the middle of the lake. The water is mostly frozen, but there are a few holes where the ice has melted. If you step into one of those holes, you'll fall into the freezing water. At this time, there's an international frisbee shortage, so it's absolutely imperative that you navigate across the lake and retrieve the disc. However, the ice is slippery, so you won't always move in the direction you intend. The surface is described using a grid like the following:

SFFF

FHFH

FFFH

HFFG


This grid is our environment where S is the agent’s starting point, and it’s safe. F represents the frozen surface and is also safe. H represents a hole, and if our agent steps in a hole in the middle of a frozen lake, well, that’s not good. Finally, G represents the goal, which is the space on the grid where the prized frisbee is located.

The agent can navigate left, right, up, and down, and the episode ends when the agent reaches the goal or falls in a hole. It receives a reward of one if it reaches the goal, and zero otherwise.

In [113]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [114]:
env = gym.make("FrozenLake-v0")

In [115]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [116]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [117]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [118]:
rewards_all_episodes = []

In [119]:
#Q learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): 

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward 
        
        if done == True: 
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        
    rewards_all_episodes.append(rewards_current_episode)
        
        

In [126]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.03200000000000002
2000 :  0.20500000000000015
3000 :  0.4080000000000003
4000 :  0.5740000000000004
5000 :  0.6130000000000004
6000 :  0.6790000000000005
7000 :  0.6930000000000005
8000 :  0.6580000000000005
9000 :  0.6800000000000005
10000 :  0.7190000000000005


In [125]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.55131314 0.53863175 0.54138128 0.53987215]
 [0.39184406 0.38068356 0.32992772 0.51599564]
 [0.45719996 0.39504968 0.42813184 0.48381665]
 [0.42162805 0.4125728  0.20825701 0.46700891]
 [0.56201155 0.46328889 0.36453463 0.34174884]
 [0.         0.         0.         0.        ]
 [0.2915622  0.104824   0.16849285 0.13676303]
 [0.         0.         0.         0.        ]
 [0.38594371 0.40922084 0.36702122 0.6129694 ]
 [0.45281051 0.62404943 0.41271388 0.32756071]
 [0.55788618 0.43076433 0.37744293 0.34318997]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41884638 0.69120947 0.69736991 0.50577766]
 [0.7930773  0.91212867 0.76178339 0.74865986]
 [0.         0.         0.         0.        ]]


In [ ]:
for episode in range(3):
    state = env.reset()
    done = False
    print("\n*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
            
        state = new_state

env.close()
        

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
